config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friands
  get 'home/about'
 #root 'home#inidex'
root 'friands#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friand.rb
class Friand < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friands_controller.rb
class FriandsController < ApplicationController
  before_action :set_friand, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index, :show]
  before_action :correct_user, only:[:edit, :update, :destroy]
  # GET /friands or /friands.json
  def index
    @friands = Friand.all
  end

  # GET /friands/1 or /friands/1.json
  def show
  end

  # GET /friands/new
  def new
    #@friand = Friand.new
    @friand = current_user.friands.build
  end

  # GET /friands/1/edit
  def edit
  end

  # POST /friands or /friands.json
  def create
    #@friand = Friand.new(friand_params)
@friand = current_user.friands.build(friand_params)
    respond_to do |format|
      if @friand.save
        format.html { redirect_to @friand, notice: "Friand was successfully created." }
        format.json { render :show, status: :created, location: @friand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friands/1 or /friands/1.json
  def update
    respond_to do |format|
      if @friand.update(friand_params)
        format.html { redirect_to @friand, notice: "Friand was successfully updated." }
        format.json { render :show, status: :ok, location: @friand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friands/1 or /friands/1.json
  def destroy
    @friand.destroy
    respond_to do |format|
      format.html { redirect_to friands_url, notice: "Friand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user
  @friand = current_user.friands.find_by(id: params[:id] )
redirect_to friands_path, notice:" wrong" if@friand.nil?

end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friand
      @friand = Friand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friand_params
      params.require(:friand).permit(:first_name, :last_name, :email, :phone, :facebook, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def inidex
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friands_helper.rb
module FriandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friands/_form.html.erb
<%= form_with(model: friand) do |form| %>
  <% if friand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friand.errors.count, "error") %> prohibited this friand from being saved:</h2>

      <ul>
        <% friand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
   
    <%= form.text_field :first_name, class:"form-control",placeholder:" First name" %>
  </div>
</br>
  <div class="field form-group">
   
    <%= form.text_field :last_name, class:"form-control",placeholder:" Last name " %>
  </div>
  </br>
  <div class="field form-group">
  
    <%= form.text_field :email, class:"form-control",placeholder:" Email " %>
  </div>
  </br>
  <div class="field form-group">
    
    <%= form.text_field :phone, class:"form-control",placeholder:" Phone " %>
  </div>
  </br>
  <div class="field form-group">
    
    <%= form.text_field :facebook, class:"form-control",placeholder:" Facebook " %>
  </div>
  <div class="field form-group">
    
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id , type: :hidden %>
  </div>

</p>
</br>
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>

  </div>
  </br>
<% end %>

app/views/friands/edit.html.erb
<h1>Editing Friend</h1>
</br>
<%= render 'form', friand: @friand %>
</br>
<%= link_to 'Show', @friand, class: "btn btn-success" %>  <%= link_to 'Delete', @friand,class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', friands_path, class: "btn btn-primary" %>

app/views/friands/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">
<thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Facebook</th>
  
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @friands.each do |friand| %>
      <% if friand.user == current_user %> 
      <tr>
        <td>
        <%= link_to friand.first_name + ' ' + friand.last_name, friand  %>
       </td>
      
        <td><%= friand.email %></td>
        <td><%= friand.phone %></td>
        <td><%= friand.facebook %></td>
      
        
       
        <td><%= link_to 'Delete', friand,class:"btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Add New', new_friand_path, class:"btn btn-success" %>
<% else %>
<h1> Welcome to Friends App</h1>
This is my first Ruby on rails App 
<% end %>

app/views/friands/new.html.erb
<h1>Add New Friend</h1>
<br/>
<%= render 'form', friand: @friand %>

<%= link_to 'Back', friands_path, class:"btn btn-primary" %>

app/views/friands/show.html.erb
<div class="card" style="width: 30rem;">
  <div class="card-body">
    <h5 class="card-title"> <%= @friand.first_name %> <%= @friand.last_name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @friand.email %></h6>
    <h6 class="card-subtitle mb-2 text-muted"> <%= @friand.phone %></h6>
    <h6 class="card-subtitle mb-2 text-muted"><%= @friand.facebook %></h6>
  
  </div>
</div>
</p>
<%= link_to 'Edit', edit_friand_path(@friand), class:"btn btn-warning" %> 
<%= link_to 'Back', friands_path, class:"btn btn-primary" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
   <%= link_to 'Friend App', root_path, class:"navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    
        <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link"  %>
      
         
       
   <% if user_signed_in? %>
   
   
   <li class="nav-item">
   <%= link_to 'Add Friend', new_friand_path, class:"nav-link"  %>
 

   </li>
   <li class="nav-item">
   <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link"  %>
 
   </li>
   <li class="nav-item">
   <%= link_to 'Edit Profil', edit_user_registration_path, class:"nav-link"  %>
 
   </li> 
   <% else %>
   <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"  %>
      
        </li>
        <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link"  %>
      </li>
      <% end %>
       

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us </h1>
This is about page

app/views/home/inidex.html.erb
<h1>Hello</h1>
this is a new Railroad

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friends APP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
  <body>
  <%= render 'home/header' %>
  <div class ="container">
</br>
  <%  if notice %>
  <%= render 'layouts/alerts' %>
  <% end %>

  <%= yield %>
</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>